### ISSUE TITLE
Using component for Nuxt compiling

### ISSUE THREAD

**Issue by shiowwj** [p4trykJ/typewriter-vue#3]
Unable to use the component on Vue.

Created Plugins file 
~/plugins/typewriter.js
`import Vue from 'vue'
import Typewriter from "typewriter-vue";

Vue.use(Typewriter, { name: 'vue-typewriter' })

console.log('plugin typewriter is locked and loaded')
`

added this to nuxt.config.js

`    plugins: [
        '~/plugins/typewriter.js'
    ],
`

Using the component on a page view:

`<template>
  <div>
    <vue-typewriter
      :replace="replace"
      :type-interval="1000"
      :replace-interval="1000"
    >
      <div>Typewriter Vue</div>
    </vue-typewriter>
  </div>
</template>
<script>

export default {
  data: () => ({
    replace: [
      { from: "Vue", to: "React?" },
    ],
  }),
};
</script>`

Still unable to get the component to render typewriter and i am not sure why.

**Comment by desdo09** [comment]
you should use ssr false

`plugins: [{ src:  '~/plugins/typewriter.js' , ssr: false } ]`,

**Comment by p4trykJ** [comment]
The reason may be SSR so you can try to use it the way @desdo09 recommends or change the plugin name to `typewriter.client.js` - both will result the same. More about client or server side only plugins can be found here: https://nuxtjs.org/docs/directory-structure/plugins#name-conventional-plugin.

**Comment by p4trykJ** [comment]
Closing this issue due to long unactivity.

**Comment by yf-hk** [comment]
How did you handle corejs incompatibility issues?

**Comment by antoniohof** [comment]
replace `Vue.use(Typewriter, { name: 'vue-typewriter' })`

with 

`Vue.component('Typewriter', Typewriter)`
